# Generated by Django 3.2.5 on 2021-07-06 21:50

from django.conf import settings
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('P', 'PayPal'), ('PS', 'PayStack'), ('R', 'Remita')], max_length=3)),
                ('amount', models.FloatField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(payments.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
