# Generated by Django 3.2.5 on 2021-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
