# Generated by Django 3.2.5 on 2021-07-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210704_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UO', 'Not Ordered'), ('P', 'Processing'), ('BD', 'Being Delivered'), ('D', 'Delivered'), ('RR', 'Refund Requested'), ('RG', 'Refund Granted')], default='UO', max_length=2),
        ),
    ]
