# Generated by Django 3.2.5 on 2021-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_image1',
            field=models.ImageField(blank=True, help_text='Additional Images If Needed', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_image2',
            field=models.ImageField(blank=True, help_text='Additional Images If Needed', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_image3',
            field=models.ImageField(blank=True, help_text='Additional Images If Needed', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
